Objetivo 1 [IV-22-23]
JoseCarlosJC/UseTime pull request #6
Opened 2022-10-26 19:43 UTC by JoseCarlosJC

# Descripción
En este objetivo se ha realizado lo siguiente:
* Descripción del uso de la aplicación en user-journeys.md
* Perfiles de los usuarios que van a usar la aplicación en tipos_usuario.md
* Historias de usuario en historias_usuario.md
* Productos mínimamente viables definidos en milestones.md (en desarrollo)
* Creación de un issue por cada historia de usuario etiquetada por *user-stories*
* Creación de un par de milestones (en desarrollo)

## Sobre los milestones
* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ]  ¿El milestone 0 es mínimo *y* viable?
* [ ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Sobre las historias de usuario
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
Sí. Para poder realizar trabajos en grupo se necesita tener un registro de los usuarios, poder acceder a sus horarios, enviar
notificaciones cuando alguien solicita un trabajo grupal con otra persona, etc.
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
Las historias de usuario son bastante cortas, ya que solo se menciona la necesidad del usuario. Por ello
se escribió un *user journey* que muestra el uso de la aplicación.
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
Los usuarios tienen unos problemas que quieren solucionar. De ahí obtienen su beneficio

2022-10-26 21:45 UTC, JoseCarlosJC commented
De momento realizo este pull request para pasar los test del objetivo 1 (saber si los paso). Quedan por hacer los milestones

2022-10-27 07:13 UTC, pablo1mc315 commented
Buenas @JoseCarlosJC se me ha asignado este repo para revisión pero veo que dices que aun que te quedan cosas por hacer, así que si quieres cuando tengas todo me mencionas y le echo un ojo 👁️

2022-10-27 07:44 UTC, JoseCarlosJC commented
Perfecto  @pablo1mc315 en cuanto esté aprobado el objetivo 1 te menciono

2022-10-27 11:06 UTC, fjromeero commented
Buenas @JoseCarlosJC  a mi también se me ha asignado para revisar tu repositorio, te comento ahora algunos cambios que puedes hacer

2022-10-27 11:12 UTC, fjromeero commented on docs/milestones.md
> +de datos para las entidades/objetos valor básicos del problema
En este milestone cambiaría para que cumpla la condición de ser un PMV

2022-10-27 11:44 UTC, pablo1mc315 commented on docs/milestones.md
> +de datos para las entidades/objetos valor básicos del problema
Concreta un poco más:

- ¿cómo sabes si hay que implementar un módulo o varios?
- Un módulo en sí no es un PMV, es decir, algo que se le pueda "entregar" al cliente y que constituya algo sobre lo que trabajar en los milestones posteriores

2022-10-27 11:54 UTC, pablo1mc315 requested changes
Te he puesto algunas cosillas que he visto convenientes, espero q te sirvan de ayuda, animo!

2022-10-27 11:54 UTC, pablo1mc315 commented on docs/milestones.md
> +y dentro de estos días las franjas horarias de estudio libres.
- No des los detalles de implementación aquí, eso se reserva para los issues posteriores.
- Pregúntate: ¿crees que este milestone es un PMV que se pueda obtener directamente a partir del M0 o, por el contrario, crees que podría haber otros PMV entre el 0 y el 1? Si la segunda pregunta es afirmativa, intenta "desmembrar" el M1 en varios milestones que puedan corresponderse PMVs

2022-10-27 11:54 UTC, pablo1mc315 commented on docs/user_journeys.md
> +Tras un día en un centro de enseñanza, el usuario tiene que realizar una serie de trabajos que tiene
¿Crees que es necesario explicar todo esto aquí?¿No crees que sería mejor exponerlo en el README principal del repositorio?

2022-10-27 20:26 UTC, JoseCarlosJC commented on docs/user_journeys.md
> +Tras un día en un centro de enseñanza, el usuario tiene que realizar una serie de trabajos que tiene
Pienso @pablo1mc315  que es mejor tenerlo dividido en dos ficheros. Si lo agrupo todo en el README principal, este podría ser muy extenso, o más de lo que me gustaría. Como idea inicial tenía pensado que el fichero README reflejase la definición de un problema y  definir la lógica de negocio para solucionarlo. Además de explicar su despliegue en la nube y hacer un seguimiento del trabajo que se va realizando, es decir, los objetivos.

El fichero *user_journeys.md* indica cómo una persona usaría la aplicación y respuestas o consecuencias que podría obtener del programa. También se ha intentado reflejar el contexto en el que la persona se encuentra para usar la app.

Por tanto, creo que es mejor tenerlo separado del README por el objetivo de cada fichero. Además, como existen enlaces a la documentación, creo que todo queda muy limpio.

2022-10-27 20:40 UTC, JoseCarlosJC commented on docs/user_journeys.md
> +Tras un día en un centro de enseñanza, el usuario tiene que realizar una serie de trabajos que tiene
Si es así, todo lo que hay antes del título *Uso de la aplicación* lo he añadido para dar una breve introducción y describir un poco el contexto en el que se encuentra el usuario a la hora de usar la app. 

¿El cómo se usaría la aplicación depende del contexto? En este caso, diría que no. Si piensas @pablo1mc315 y también @fjromeero  que esto se podría omitir, que no aporta nada, confunde, etc., podría quitarse de este fichero sin problemas

2022-10-27 21:51 UTC, pablo1mc315 commented on docs/user_journeys.md
> +Tras un día en un centro de enseñanza, el usuario tiene que realizar una serie de trabajos que tiene
me refería al fichero en general, pero obviamente no digo que lo quites, solo que le echases un ojo a ver si hay cosas que estas repitiendo en ambos y que igual no son necesarias, pero igualmente lo veo bien, no es algo que afecte directamente al objetivo

2022-10-28 07:57 UTC, JoseCarlosJC commented on docs/milestones.md
> +de datos para las entidades/objetos valor básicos del problema
¡Ya he cambiado el milestone 0 @pablo1mc315  @fjromeero ! Para expresar un producto he indicado que deben ser ficheros (fichero con código) y una guía breve para saber si lo que se está haciendo o ya se ha hecho está bien o no

2022-10-28 08:03 UTC, JoseCarlosJC commented on docs/milestones.md
> +y dentro de estos días las franjas horarias de estudio libres.
Al igual que el milestone 0 @pablo1mc315 , he cambiado este para indicar qué se espera que haga este producto.

2022-10-28 08:03 UTC, JoseCarlosJC commented on docs/milestones.md
> +y dentro de estos días las franjas horarias de estudio libres.
Para tu segunda cuestión @pablo1mc315 , sigo pensando en ello

2022-10-28 08:04 UTC, fjromeero commented on docs/milestones.md
> +Clase o clases que implementen la lógica de negocio: los trabajos se dividen en tareas que serán distribuidas en los días venideros de manera que se terminen antes de su fecha de finalización.
No se si es la mejor manera de expresar la implementación de la lógica de negocio con clases compilables

2022-10-28 08:04 UTC, fjromeero commented
El resto lo veo correcto

2022-10-28 08:12 UTC, JoseCarlosJC commented on docs/user_journeys.md
> +Tras un día en un centro de enseñanza, el usuario tiene que realizar una serie de trabajos que tiene
Vale @pablo1mc315 . Es que tenía la duda de si era esa parte del fichero o todo el fichero.

En ese caso, pienso que la separación de contenido en los dos ficheros deja una estructura más limpia. No me gustaría que el README fuera tan largo, ya que conforme se vaya trabajando se irá añadiendo información. En el README hay una descripción del problema, se describe la lógica de negocio, posibles ideas, por qué su despliegue en la nube, etc., y el fichero user_journeys.md describe el uso de la aplicación por parte de los usuarios y el contexto en el que lo utilizan

2022-10-28 08:23 UTC, JoseCarlosJC commented on docs/milestones.md
> +Clase o clases que implementen la lógica de negocio: los trabajos se dividen en tareas que serán distribuidas en los días venideros de manera que se terminen antes de su fecha de finalización.
Te entiendo y tiene sentido. Lo he cambiado ya

2022-10-28 08:24 UTC, fjromeero commented
@JoseCarlosJC Ok yo lo veo bien 👍 . Si quieres ya puedes pedirle la revisión a @JJ

2022-10-28 08:36 UTC, pablo1mc315 approved these changes
Por mi parte todo correcto, si crees que está bien así repartido en dos ficheros (user-journey y readme) no tengo más que añadir 😁

2022-10-29 15:10 UTC, JoseCarlosJC commented
Listo para revisión @JJ

2022-10-30 08:45 UTC, JJ requested changes
Muy cerca, pero un algoritmo no es un producto.

2022-10-30 08:45 UTC, JJ commented on README.md
> +una rutina establecida te ayudará a concentrarte solo en los ejercicios y así
Por favor, no añadáis ruido al PR con cambios en ficheros que no tienen nada que ver con el mismo. Hacedlo antes o después.

2022-10-30 08:45 UTC, JJ commented on README.md
> -* En la programación estaba terminar una serie de tareas tal día y no lo has cumplido
No entiendo por qué has quitado esto. ¿Tiene algo que ver con este objetivo?

2022-10-30 08:45 UTC, JJ commented on README.md
> +# Objetivo 1
El readme es el de un proyecto, no el de una asignatura. Tratad de evitar referencias a una asignatura en el mismo. Podéis hacer referencias a milestones y demás, pero en general lo que tenéis que hacer es describir el proyecto en el estado actual.

2022-10-30 08:45 UTC, JJ commented on docs/glosario.md
> +* **trabajo**: actividad pertenececiente a un ámbito, por ejemplo el nombre de una asignatura, que tiene una fecha de entrega. Los trabajos
:clap:

2022-10-30 08:45 UTC, JJ commented on docs/glosario.md
> +* **tarea**: actividad que tienen una fecha y hora de inicio y final. Las tareas se realizan para completar los trabajos.
Molaría más si pusieras mayúscula al principio de frase.

2022-10-30 08:45 UTC, JJ commented on docs/historias_usuario.md
> +Juan Alberto necesita una planificación para saber cuántas horas tiene que estudiar en casa los días
¿Qué beneficio persigue tiene este usuario?

2022-10-30 08:45 UTC, JJ commented on docs/milestones.md
> +## [M0] Fichero/s que representen un modelo de problema
Me gustaría que dejárais de poner palabras mágicas como "ficheros". Lo importante aquí es el modelo del problema. En la descripción podéis indicar cómo tiene que entregarse (el *producto*) pero el producto no son "ficheros", sino el modelo.

2022-10-30 08:45 UTC, JJ commented on docs/milestones.md
> +Algoritmo implementen la lógica de negocio: los trabajos se dividen en tareas que serán distribuidas en los días venideros de manera que se terminen antes de su fecha de finalización.
¿Cómo se entrega ese algoritmo?

2022-10-30 09:53 UTC, JoseCarlosJC commented on README.md
> +una rutina establecida te ayudará a concentrarte solo en los ejercicios y así
Entiendo que estos cambios entonces se deberían de hacer por ejemplo en la rama main (porque son cambios de palabras), con los commits necesarios, o abriendo un nuevo pull request cuya descripción sea la de mejorar las expresiones del lenguaje, etc., para no mezclar el objetivo de este pull request con cambios que no tienen que ver con este

2022-10-30 09:59 UTC, JoseCarlosJC commented on README.md
> -* En la programación estaba terminar una serie de tareas tal día y no lo has cumplido
No tiene que ver con este objetivo. La próxima vez los cambios de este tipo los realizaré antes o después

2022-10-30 10:09 UTC, JoseCarlosJC commented on README.md
> +# Objetivo 1
Se refiere a que al usar la organización en *objetivo 0*, *objetivo 1* ... parece más una asignatura que un proyecto, ¿no?

2022-10-30 10:13 UTC, JJ commented on README.md
> +una rutina establecida te ayudará a concentrarte solo en los ejercicios y así
Correcto.

2022-10-30 10:14 UTC, JJ commented on README.md
> +# Objetivo 1
Correcto.

2022-10-30 10:30 UTC, JoseCarlosJC commented on docs/glosario.md
> +* **tarea**: actividad que tienen una fecha y hora de inicio y final. Las tareas se realizan para completar los trabajos.
¿Mayúscula en la palabra que se va a definir o la que comienzo a la descripción?

He estado mirando glosarios, y he encontrado esto en la documentación de Github 
![glosario_github](https://user-images.githubusercontent.com/72255802/198873994-9299fa99-c122-43ec-8259-39aee0579438.png)

2022-10-30 10:34 UTC, JJ commented
En la que comienza la descripción de cada item, claro.

2022-10-30 10:48 UTC, JoseCarlosJC commented on docs/historias_usuario.md
> +Juan Alberto necesita una planificación para saber cuántas horas tiene que estudiar en casa los días
Juan Alberto no estudia, en un principio, los martes y jueves porque tiene entrenamiento. Por ello hace el sacrificio de estudiar 6 horas los lunes, miércoles, viernes y los sábados o domingos, solo uno de los dos, debido a que tiene partido un día del fin de semana.

Entonces conforme vaya apuntando sus trabajos , el programa calculará/estimará el tiempo total necesario para terminarlos. Si el tiempo que necesita es mayor al que tiene disponible, que se calcula sabiendo las franjas horarias de estudio del usuario, el sistema notificará al usuario de que tiene que dedicar *x* horas más para terminar los trabajos.

Juan Alberto quiere saber si le dará tiempo a terminar todos sus trabajos con la configuración que él ha determinado. Si
el sistema le avisa que no, entonces él tomará la decisión de no ir a entrenar uno de los días y añadir esas horas de estudio necesarias que le indica el sistema el día que falte al entrenamiento.

También el sistema tendrá en cuenta un umbral para el tiempo necesario de estudio. Si este es de 20  horas y el disponible es de 18, por ejemplo, puede notificar solo que será una semana muy apretada y mostrar como resultado un horario

2022-10-30 10:50 UTC, JJ commented on docs/historias_usuario.md
> +Juan Alberto necesita una planificación para saber cuántas horas tiene que estudiar en casa los días
¿Por qué me cuentas esto aquí? Los cambios, al repositorio.

2022-10-30 12:19 UTC, JoseCarlosJC commented
!Listo para revisión @JJ!
Cambios realizados:
* En la descripción de los milestones se especifica cómo se han de entregar los productos y no en el título
* Nuevo formato del glosario
*  HU02 más detallada

2022-10-30 12:23 UTC, JoseCarlosJC commented on docs/historias_usuario.md
> +Juan Alberto necesita una planificación para saber cuántas horas tiene que estudiar en casa los días
Porque pensaba que era una duda y no para realizar un cambio en la descripción del fichero 😄

2022-10-30 16:54 UTC, JJ approved these changes
:+1:

2022-11-01 17:22 UTC, merged