[IV-22-23] Objetivo 2
JoseCarlosJC/UseTime pull request #8
Opened 2022-11-03 12:22 UTC by fjromeero

2022-11-05 17:22 UTC, JoseCarlosJC commented
Comentarios:
* Para el modelo de usuario propuesto, has definido un conjunto de rutinas de manera que en las horas especificadas **nunca** estudiará el usuario. Resalto nunca porque no se especifica ningún día, por tanto entiendo que es para todos los días. Por esta parte habría que replantear el modelo de usuario (abriendo un issue por ejemplo para determinar que es un usuario o cómo saber cuándo puede o no puede estudiar). Por el resto de esta clase, lo veo bien👍
* A raíz del punto anterior, la clase Rutina dependerá de lo que se decida en Usuario, ya que  es la única clase que utiliza rutinas.
* ¿Los trabajos compartidos entre varios usuarios están reflejados en el modelo?  Es cierto que varios usuarios podrían tener el mismo trabajo según este modelo. Si es así, por favor escríbeme o documéntame cuál ha sido tu idea para abordar este problema, la solución propuesta, etc.
* Que un trabajo tenga asociadas las tareas en las que se divide lo veo perfecto 👍.
* Veo que has usado el tipo de dato Date que indica tanto el día como la hora. Por tanto para una tarea se puede saber cúando se acaba y cúando se termina. Cumple con lo que se indica 👍

2022-11-11 08:52 UTC, fjromeero commented
@JoseCarlosJC  listo para revision

2022-11-11 16:15 UTC, JoseCarlosJC commented
La clase *HuecosLibres* entiendo que representa ese horario que indica cuándo puede estudiar un usuario. ¿Cómo puedo saber si un intervalo está ya ocupado por una Tarea o no? Una posible opción sería eliminar ese intervalo. Pero si se necesita reorganizar las tareas, necesitamos volver a tener esas horas disponibles (para volver a distribuir las tareas). Podemos coger las horas de las tareas y añadirlas de nuevo al intervalo , ¿no?.

2022-11-11 16:21 UTC, fjromeero commented
> La clase _HuecosLibres_ entiendo que representa ese horario que indica cuándo puede estudiar un usuario. ¿Cómo puedo saber si un intervalo está ya ocupado por una Tarea o no? Una posible opción sería eliminar ese intervalo. Pero si se necesita reorganizar las tareas, necesitamos volver a tener esas horas disponibles (para volver a distribuir las tareas). Podemos coger las horas de las tareas y añadirlas de nuevo al intervalo , ¿no?.
> 
> Para saber si un intervalo está ocupado, ¿tengo que comparar con los huecos ocupados del usuario, el atributo llamado huecosLibres? Es decir, mirar en esa estructura, comparar si el día que quiero mirar existe, y si existe, mirar que coincide el intervalo?

Para saber si un intervalo esta ocupado o no se puede implementar con los intervalos de las tareas creadas

2022-11-11 16:44 UTC, JoseCarlosJC commented
¿Qué te parece tener dos campos en la clase Trabajo, uno para el título y otra para la actividad en sí?
¿Y lo mismo para las Tareas: un campo que sea el título y otro que indique la actividad?
Lo que pienses que sea mejor, más cómodo, etc.

2022-11-11 16:48 UTC, JoseCarlosJC commented
Te recomiendo cambiar el nombre de la clase *HuecosLibres* por *HuecosDia*, *IntervaloDia* ... o similar porque al indicar la palabra *Libres* hace que sea una restricción a nivel semántico, por entendimiento vaya.

¿Y el atributo #huecosLibres de Usuario llamarlo por ejemplo #huecosOcupados o #franjasOcupadas o #intervalosOcupados? Ya que en el comentario sobre ese atributo se indica que siempre serán intervalos ocupados

2022-11-11 16:54 UTC, fjromeero commented
> Te recomiendo cambiar el nombre de la clase _HuecosLibres_ por _HuecosDia_, _IntervaloDia_ ... o similar porque al indicar la palabra _Libres_ hace que sea una restricción a nivel semántico, por entendimiento vaya.
> 
> ¿Y el atributo #huecosLibres de Usuario llamarlo por ejemplo #huecosOcupados o #franjasOcupadas o #intervalosOcupados? Ya que en el comentario sobre ese atributo se indica que siempre serán intervalos ocupados

Claro sin problema

2022-11-11 17:48 UTC, fjromeero commented
Listo @JoseCarlosJC  la cambié de HuecosLibres a HuecosLIbresDiay modfique lo de la documentacion de la clase

2022-11-14 12:16 UTC, fjromeero commented
> @fjromeero por lo que hemos hablado en persona, entiendo que lo llames HuecosLibres ya que el objetivo de la clase era solo representar los huecos libres y para conocer las horas ocupadas lo miramos en las tareas 👍
> 
> ¡El archivo iv.yaml hay que actualizarlo eso sí!

2022-11-14 12:20 UTC, fjromeero commented
> @fjromeero por lo que hemos hablado en persona, entiendo que lo llames HuecosLibres ya que el objetivo de la clase era solo representar los huecos libres y para conocer las horas ocupadas lo miramos en las tareas 👍
> 
> ¡El archivo iv.yaml hay que actualizarlo eso sí!

Hecho @JoseCarlosJC

2022-11-14 12:26 UTC, JoseCarlosJC approved these changes

2022-11-14 12:26 UTC, JoseCarlosJC commented on iv.yaml
> +  - src/HuecosLIbresDia.ts
*HuecosLibres*, que has puesto una mayúscula de más

2022-11-18 23:22 UTC, fjromeero commented
Listo para revisión @JoseCarlosJC

2022-11-19 18:14 UTC, JoseCarlosJC reviewed
👍

2022-11-19 18:15 UTC, JoseCarlosJC approved these changes

2022-11-19 19:07 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-19 21:19 UTC, fjromeero commented
Revisando otra vez, vi que se me olvidaron los getters de la clase Hora ahora ya están @JoseCarlosJC

2022-11-21 11:55 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-21 16:55 UTC, JJ commented
> Sobre la estructura del repositorio:
> 
>     * [heavy_check_mark  ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y disposición de los mismos?
> 
> 
> Sobre el análisis del problema:
> 
>     * [heavy_check_mark ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
> 
>     * [heavy_check_mark ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?
> 
>     * [ heavy_check_mark] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?.
> 
> 
> Sobre la planificación y la programación:
> 
>     * [ heavy_check_mark] ¿Los issues representan un problema, y no una tarea?

No, simplemente ponen un nombre de una clase (en algunos casos)
> 
>     * [ heavy_check_mark] ¿Todos los issues creados están asignados a una HU?

No, no lo están, y os rogaría que no marquéis lo que no habéis hecho.
> 
>     * [ heavy_check_mark] ¿Todos los cambios en el código están asignados a un issue al que se referencia en un commit? 

Tampoco; por ejemplo 575553b7dfcc92c0e7b3bcadee55db2b2ac2551c

2022-11-21 16:58 UTC, JJ requested changes
Sin seguir una metodología correcta, es imposible llegar a un resultado correcto.
Por favor, revisa los errores comunes y objetivos de aprendizaje de las últimas semanas.
A @JoseCarlosJC: por favor revisa los errores comunes del objetivo 2 para vosotros. Uno de ellos es que comprobéis la lista de comprobación, si se ha llevado a cabo o no.

2022-11-21 16:58 UTC, JJ commented on src/hora.ts
> +    get hora(){
Ninguna referencia a ningún issue.

2022-11-21 16:58 UTC, JJ commented on src/hora.ts
> +        return this.#hora
¿Seguro que esto es sintácticamente correcto?

2022-11-21 16:58 UTC, JJ commented on src/hora.ts
> +    #hora : number;
Esto es Javascript, no Typescript. Por favor, consulta la sintaxis de TypeScript

2022-11-21 17:28 UTC, fjromeero commented on src/hora.ts
> +    #hora : number;
No comprendo a que se refiere

2022-11-21 17:29 UTC, fjromeero commented on src/hora.ts
> +    #hora : number;
> Esto es Javascript, no Typescript. Por favor, consulta la sintaxis de TypeScript

No comprendo a que se refiere

2022-11-21 17:31 UTC, fjromeero commented on src/hora.ts
> +        return this.#hora
> ¿Seguro que esto es sintácticamente correcto?

Si se refiere a la sintaxsis del getter, lo busqué en el sitio oficial de Typescript

2022-11-21 17:31 UTC, fjromeero commented on src/hora.ts
> +    get hora(){
Fallo mio

2022-11-21 17:47 UTC, JJ commented on src/hora.ts
> +        return this.#hora
OK, lo ha incorporado desde la versión 3.8. :+1: No lo sabía.

2022-11-21 17:48 UTC, JJ commented on src/hora.ts
> +    #hora : number;
Typescript es un superconjunto de JavaScript,  y como tal [puede usar la sintaxis de ECMAscript para atributos privados](https://www.typescriptlang.org/docs/handbook/classes.html)
Sin embargo, TypeScript tiene una forma mucho más razonable para expresar esos atributos privados. Como mejor práctica, siempre conviene seguir las convenciones del propio lenguaje.

2022-11-21 17:52 UTC, fjromeero commented on src/hora.ts
> +    #hora : number;
> Typescript es un superconjunto de JavaScript, y como tal [puede usar la sintaxis de ECMAscript para atributos privados](https://www.typescriptlang.org/docs/handbook/classes.html) Sin embargo, TypeScript tiene una forma mucho más razonable para expresar esos atributos privados. Como mejor práctica, siempre conviene seguir las convenciones del propio lenguaje.

De acuerdo hice uso de # porque leí en el sitio de Typescript que con el uso de "private" se conseguía una privacidad más suave que la que se conseguía con el uso de "#" por eso pensé que sería una buena idea usarlo, pero lo cambio sin problema

2022-11-21 17:56 UTC, JJ commented on src/hora.ts
> +    #hora : number;
Er. No creo. ¿Suave, por qué? El transpilador que pase a JS usará `#` para private. `private` existe antes que eso, claro, y antes usarían algún tipo de mecanismo de ofuscación para conseguir lo mismo (seguramente también JS lo use, no creo que sea "fuerte" de ninguna manera)
En todo caso
1. Tendrías que haberlo planteado en el problema == issue
2. Tendrías que haberlo aclarado en el mensaje de commit que resolviera el problema
3. En cualquier caso, mejores prácticas >> temas ofuscados de prestaciones.

2022-11-21 17:59 UTC, fjromeero commented on src/hora.ts
> +    #hora : number;
De acuerdo, gracias por por corregirme

2022-11-21 17:59 UTC, fjromeero commented on src/hora.ts
> +    #hora : number;
> Er. No creo. ¿Suave, por qué? El transpilador que pase a JS usará `#` para private. `private` existe antes que eso, claro, y antes usarían algún tipo de mecanismo de ofuscación para conseguir lo mismo (seguramente también JS lo use, no creo que sea "fuerte" de ninguna manera) En todo caso
> 
> 1. Tendrías que haberlo planteado en el problema == issue
> 2. Tendrías que haberlo aclarado en el mensaje de commit que resolviera el problema
> 3. En cualquier caso, mejores prácticas >> temas ofuscados de prestaciones.

De acuerdo, gracias por corregirme

2022-11-22 00:05 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-22 06:29 UTC, JJ requested changes
Por favor, revisa el concepto de producto mínimamente viable.
En ese sentido, No me parece que a este nivel haya que distinguir entre "trabajo" y "tarea", pero no es cosa mía.

2022-11-22 06:29 UTC, JJ commented on src/hora.ts
> +    get hora(){
Si no hay ninguna referencia a ningún issue, el código no es válido.

2022-11-22 06:29 UTC, JJ commented on src/usuario.ts
> +    private _correo: string;
¿Qué historia de usuario pide esto?

2022-11-22 06:29 UTC, JJ commented on src/usuario.ts
> +    private _password: string;
Clave ¿para qué? ¿En qué PMV está incluido esto?

2022-11-22 09:38 UTC, fjromeero commented on src/usuario.ts
> +    private _password: string;
> Clave ¿para qué? ¿En qué PMV está incluido esto?
Es cierto, esto sobra totalmente no se como no me he dado cuenta

2022-11-22 22:41 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-23 06:38 UTC, JJ commented
[Close](https://github.com/JoseCarlosJC/UseTime/pull/8/commits/42fc2fe264100804acacd41059042b19ffdaee53) https://github.com/JoseCarlosJC/UseTime/issues/12 [creada clase que resuelve el problema](https://github.com/JoseCarlosJC/UseTime/pull/8/commits/42fc2fe264100804acacd41059042b19ffdaee53) no corresponde a ninguna buena práctica. ¿Por qué resuelve el problema? Los mensajes de commit deben ser informativos y documentar el código.

2022-11-23 06:39 UTC, JJ commented
El resto del mensaje dice qué se ha hecho, cuando eso ya es evidente por el código. Debe decir por qué se ha hecho eso y por qué se piensa que es una solución.

2022-11-23 06:46 UTC, JJ requested changes
El código propuesto sigue sin solucionar los problemas, aparte de que no se ha hecho nada sobre comentarios anteriores.
También os pediría que siguiérais buenas prácticas en los mensajes de commit.

2022-11-23 06:46 UTC, JJ commented on src/usuario.ts
> +    private _correo: string;
:arrow_double_up:

2022-11-23 06:46 UTC, JJ commented on src/hora.ts
> +export class Hora{
Esto no resuelve #14. Aparte de que te has limitado a cambiar la sintaxis, varios problemas más
* El nombre es tan genérico que no permite ver que se refiere al *comienzo* de un tramo horario
* Problema adicional es que lo estás usando no sólo para "comienzo" de un tramo, sino también para su *final* (como se ve más abajo porque los tramos son arrays de hora de comienzo y hora de final)
* No solucionas la parte de "cuanto va a ser su duración".
* Tampoco solucionas el problema real, ya mencionado, que es cuando puede realmente empezar. ¿Puede empezar un tramo horario a las 22:37?

2022-11-23 08:49 UTC, fjromeero commented on src/hora.ts
> +export class Hora{
> Esto no resuelve #14. Aparte de que te has limitado a cambiar la sintaxis, varios problemas más
> 
> * El nombre es tan genérico que no permite ver que se refiere al _comienzo_ de un tramo horario
> * Problema adicional es que lo estás usando no sólo para "comienzo" de un tramo, sino también para su _final_ (como se ve más abajo porque los tramos son arrays de hora de comienzo y hora de final)
> * No solucionas la parte de "cuanto va a ser su duración".
> * Tampoco solucionas el problema real, ya mencionado, que es cuando puede realmente empezar. ¿Puede empezar un tramo horario a las 22:37?

Yo creo que si resuelve porque esta clase Hora al usarlo en un array de hora comienzo y hora final, permita que comience, y termine  a cualquier hora ( al poder termina a cualquier hora permite que la duración pueda ser cualquiera)

En cuanto , a cuando realmente puede empezar, pienso que esa es una decisión en la lógica de negocio y no mía, a mi no me influye si comienza a la 22:37 o a las 08:00 , yo con esta solución permito que los tramos horarios comiencen cada hora en punto, media, o a la hora que sea

2022-11-23 08:49 UTC, fjromeero commented
> El resto del mensaje dice qué se ha hecho, cuando eso ya es evidente por el código. Debe decir por qué se ha hecho eso y por qué se piensa que es una solución.

De acuerdo

2022-11-23 08:52 UTC, fjromeero commented on src/usuario.ts
> +    private _correo: string;
> ¿Qué historia de usuario pide esto?

En #16 , como explico, en la HU3 #5  se dice que se podrán crear tareas en grupo, por lo que considero que para resolverlo necesitamos poder identificar individualmente a los usuarios.

2022-11-23 09:30 UTC, JJ commented on src/hora.ts
> +export class Hora{
> > Esto no resuelve #14. Aparte de que te has limitado a cambiar la sintaxis, varios problemas más
> > 
> > * El nombre es tan genérico que no permite ver que se refiere al _comienzo_ de un tramo horario
> > * Problema adicional es que lo estás usando no sólo para "comienzo" de un tramo, sino también para su _final_ (como se ve más abajo porque los tramos son arrays de hora de comienzo y hora de final)
> > * No solucionas la parte de "cuanto va a ser su duración".
> > * Tampoco solucionas el problema real, ya mencionado, que es cuando puede realmente empezar. ¿Puede empezar un tramo horario a las 22:37?
> 
> Yo creo que si resuelve porque esta clase Hora al usarlo en un array de hora comienzo y hora final, permita que comience, y termine a cualquier hora ( al poder termina a cualquier hora permite que la duración pueda ser cualquiera)
> 

No, no lo resuelve. Para empezar, no estás modelizando un "tramo". Estás modelizando la hora de comienzo del tramo. Para seguir, estás diciendo que un tramo está marcado por dos `Hora`s. Si es así, lo correcto es que crees un objeto valor que modelice ese tramo, pero es bastante absurdo crear dos objetos valor para una cosa que se puede modelizar por uno solo. 

Dicho de otro modo: si una `Hora`  siempre la vas a usar con otra `Hora` (en el array) es que los dos deben estar en el mismo objeto.

> En cuanto , a cuando realmente puede empezar, pienso que esa es una decisión en la lógica de negocio y no mía, a mi no me influye si comienza a la 22:37 o a las 08:00 , yo con esta solución permito que los tramos horarios comiencen cada hora en punto, media, o a la hora que sea

No, es una decisión del modelo y de la persona que lo hace mirando a la historia de usuario. Que no se refiere a los horarios de llegada de un tren a un apeadero, sino a tareas de gente.

2022-11-23 09:35 UTC, fjromeero commented on src/hora.ts
> +export class Hora{
> > > Esto no resuelve #14. Aparte de que te has limitado a cambiar la sintaxis, varios problemas más
> > > 
> > > * El nombre es tan genérico que no permite ver que se refiere al _comienzo_ de un tramo horario
> > > * Problema adicional es que lo estás usando no sólo para "comienzo" de un tramo, sino también para su _final_ (como se ve más abajo porque los tramos son arrays de hora de comienzo y hora de final)
> > > * No solucionas la parte de "cuanto va a ser su duración".
> > > * Tampoco solucionas el problema real, ya mencionado, que es cuando puede realmente empezar. ¿Puede empezar un tramo horario a las 22:37?
> > 
> > 
> > Yo creo que si resuelve porque esta clase Hora al usarlo en un array de hora comienzo y hora final, permita que comience, y termine a cualquier hora ( al poder termina a cualquier hora permite que la duración pueda ser cualquiera)
> 
> No, no lo resuelve. Para empezar, no estás modelizando un "tramo". Estás modelizando la hora de comienzo del tramo. Para seguir, estás diciendo que un tramo está marcado por dos `Hora`s. Si es así, lo correcto es que crees un objeto valor que modelice ese tramo, pero es bastante absurdo crear dos objetos valor para una cosa que se puede modelizar por uno solo.
> 
> Dicho de otro modo: si una `Hora` siempre la vas a usar con otra `Hora` (en el array) es que los dos deben estar en el mismo objeto.

De acuerdo, lo acabo de entender.

> 
> > En cuanto , a cuando realmente puede empezar, pienso que esa es una decisión en la lógica de negocio y no mía, a mi no me influye si comienza a la 22:37 o a las 08:00 , yo con esta solución permito que los tramos horarios comiencen cada hora en punto, media, o a la hora que sea
> 
> No, es una decisión del modelo y de la persona que lo hace mirando a la historia de usuario. Que no se refiere a los horarios de llegada de un tren a un apeadero, sino a tareas de gente.

Pero en las historias de usuario no se aborda cuando un tramo puede comenzar ni de cuanto puede ser sus duraciones

2022-11-23 10:10 UTC, JJ commented on src/hora.ts
> +export class Hora{
> > No, es una decisión del modelo y de la persona que lo hace mirando a la historia de usuario. Que no se refiere a los horarios de llegada de un tren a un apeadero, sino a tareas de gente.
> 
> Pero en las historias de usuario no se aborda cuando un tramo puede comenzar (si a en punto, y media,. ...) ni de cuanto puede ser sus duraciones (horas completas, horas y minutos, minutos)

¿Ves cómo tienes que plantear el problema entonces y proponer una solución?

2022-11-23 10:21 UTC, fjromeero commented on src/hora.ts
> +export class Hora{
> > > No, es una decisión del modelo y de la persona que lo hace mirando a la historia de usuario. Que no se refiere a los horarios de llegada de un tren a un apeadero, sino a tareas de gente.
> > 
> > 
> > Pero en las historias de usuario no se aborda cuando un tramo puede comenzar (si a en punto, y media,. ...) ni de cuanto puede ser sus duraciones (horas completas, horas y minutos, minutos)
> 
> ¿Ves cómo tienes que plantear el problema entonces y proponer una solución?

De acuerdo 👍

2022-11-24 19:38 UTC, JoseCarlosJC commented
Por lo que veo y entiendo, los huecos libres serán de hora en hora, por ejemplo [16,17,18] y no tengo en cuenta los minutos porque no hace falta. Y la tareas pueden ser de media hora o una según su dificultad, especificada en el trabajo. Es viable sí

2022-11-24 19:41 UTC, JoseCarlosJC commented
Ahora siguiendo lo anterior, si las tareas solo podrán ser de media hora o una hora según la dificultad, el enumerado **Complejidad** lo reduciría a dos valores ¿no?

2022-11-24 19:52 UTC, JoseCarlosJC commented
Lo siguiente que voy a decir, si quieres espérate al profesor, pero si la clase Tarea va a ser de 30 o 60 minutos, haría una comprobación de que el tramo horario que se le pasa para construir una tarea sea de esas duraciones, y sino, que no se cree. O por ejemplo que solo dé la opción de crear dos tipos de tareas, las de 30 minutos o las de 60, sin estar pasando tramos horarios que sean correctos o no.

2022-11-24 19:55 UTC, JoseCarlosJC commented
Y que en la descripción de la clase Tarea, en los comentarios, también especificaría esa característica de que son tareas de media hora o una

2022-11-24 19:57 UTC, JoseCarlosJC commented
Los commits son descriptivos y me ayudan a seguir y a entender el proceso que estás realizando 👍

2022-11-24 21:17 UTC, fjromeero commented
> Ahora siguiendo lo anterior, si las tareas solo podrán ser de media hora o una hora según la dificultad, el enumerado **Complejidad** lo reduciría a dos valores ¿no?

No necesariamente, se puede mantener los tres valores de complejidad, que según entendí en las user journeys se usan para asignar más o menos horas a un trabajo y por lo consiguiente mas tareas. Por lo que al ya estar las puedes usar también para crear tareas con un tramo de tiempo mas o menos largo

2022-11-24 21:18 UTC, fjromeero commented
> Por lo que veo y entiendo, los huecos libres serán de hora en hora, por ejemplo [16,17,18] y no tengo en cuenta los minutos porque no hace falta. Y la tareas pueden ser de media hora o una según su dificultad, especificada en el trabajo. Es viable sí

Si, esa es la idea en principio

2022-11-24 21:24 UTC, JoseCarlosJC commented
> > Ahora siguiendo lo anterior, si las tareas solo podrán ser de media hora o una hora según la dificultad, el enumerado **Complejidad** lo reduciría a dos valores ¿no?
> 
> No necesariamente, se puede mantener los tres valores de complejidad, que según entendí en las user journeys se usan para asignar más o menos horas a un trabajo y por lo consiguiente mas tareas. Por lo que al ya estar las puedes usar también para crear tareas con un tramo de tiempo mas o menos largo

Vale, es cierto lo de los trabajos, que ya no lo recordaba

2022-11-24 21:48 UTC, JoseCarlosJC commented
He comprobado la sintaxis de los ficheros. Todos son correctos menos el de **usuario.ts**. El error es que hay atributos que no han sido inicializados. Este error se da porque a partir de la versión 2.7 de Typescript se añadió un flag que hace que sea obligatoria la inicialización de atributos de las clases. Para solventar este error se puede actuar de  muchas maneras; por ejemplo en trabajo.js lo haces para inicializar las tareas.

2022-11-25 11:20 UTC, fjromeero commented
Listo para revisión @JoseCarlosJC

2022-11-28 10:34 UTC, JoseCarlosJC requested changes

2022-11-28 11:02 UTC, fjromeero commented on src/tarea.ts
> +            this._tramo = new TramoHorario([horaInicio,0],[horaInicio,30])
> De esta manera se puede crear una tarea a las 16,0 y terminar a las 16,30 pero no se puede crear ninguna tarea que empiece a las 16,30 hasta las 17,0

Listo para revisión

2022-11-28 12:27 UTC, JoseCarlosJC approved these changes
Ya estaría todo listo 👍

2022-11-28 15:22 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-28 16:36 UTC, JJ requested changes
Aparte de problemas de la modelización, el problema principal es que estás incluyendo código que no contribuye a este milestone.

2022-11-28 16:36 UTC, JJ commented on src/huecos_libres_dia.ts
> +    constructor(dia: Date, intervalos: Array<TramoHorario>){
Vamos a ver. Esto no tiene nada que ver con el objetivo, pero piensa un poco. `dia` e `intervalos` son argumentos para el constructor, lo que significa que, quien quiera que cree el objeto, va a poder acceder públicamente a sus valores. ¿Tiene algún sentido que los pongas como privados?
Mira, por favor, los [errores frecuentes de esta semana](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-12.md#objetivo-2).
En general, el código debe añadir valor a los datos que encapsule; una forma de añadir valor es calcular o crear otros datos a partir de los existentes, de forma que no haya que calcularlos (repetidamente) más adelante. En este caso, parece claro que no añade ningún valor. Los agrupa (pero ya lo estarían donde quiera que se le haya llamado) y los cambia de nombre. ¿Qué valor tiene eso?

Es más, es que la clase se llama `HuecosLibresDia`. ¿Dónde están esos huecos libres? Si ya están en `intervalos`, ¿para qué los metes aquí?

En general, todo código tiene un propósito. Si no entiendes cuál es ese propósito, y te estás limitando a trasladar los objetos y atributos que se te hayan ocurrido, no estás entendiendo el propósito del código.

Y para entender el propósito hay que plantear el problema. Qué datos se tienen, qué datos se quieren obtener, y a partir de ahí, decidir qué hay que almacenar.

2022-11-28 16:36 UTC, JJ commented on src/huecos_libres_dia.ts
> +    private _intervalos: Array<TramoHorario>
Fíjate en el issue #13 que es con el que estás trabajando. Plantea un problema, y ahí está la cosa más o menos clara. Sin embargo, dice "el usuario tenga cosas que hacer en cada momento".
Tenemos dos problemas aquí.
El primero se resuelve con domain driven design: ese te dice que tienes que tener un lenguaje común entre el dominio del problema y el código. Sin embargo, en el dominio del problema hablas de "cosas que haya que hacer en ese momento" y aquí de "intervalos". ¿Qué contiene esto? ¿Las cosas que tiene que hacer en cada momento? ¿O, como dice la clase, HuecosLibresDia? Pero aparentemente le estás asignando (abajo) simplemente lo que le pasan en el constructor.
Mira de nuevo [los errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-12.md#objetivo-2). *Los argumentos de un constructor no tienen por qué ser directamente lo que se use como atributo*. Mira también los otros comentarios. ¿Te parece que habría algún valor para el cliente que añadir aquí?

2022-11-28 16:36 UTC, JJ commented on src/tarea.ts
> +    private _dia: Date;
¿En que se llevará a cabo? ¿O en el que tiene que terminar?

2022-11-28 16:36 UTC, JJ commented on src/tramo_horario.ts
> +    private _horaComienzo : [number, number];
Si no vas a usar un bucle para recorrerlo, no uses un array para representarlo, usa un diccionario. Es más informativo y claro `.hora` y `.minuto` que [0] y [1]

2022-11-28 16:36 UTC, JJ commented on src/usuario.ts
> +    private _correo: string;
No está en este milestone (de hecho, no está en ningún milestone). Limitaros a modelizar lo que se vaya a incluir en este producto mínimamente viable.

2022-11-28 18:09 UTC, fjromeero commented on src/tarea.ts
> +    private _dia: Date;
> ¿En que se llevará a cabo? ¿O en el que tiene que terminar?

En el que se llevan a cabo, son tareas no trabajos, que como planteé en el issue serán de como mucho 1 hora, no le encuentro sentido a hablar de un dia de finalización

2022-11-28 18:10 UTC, fjromeero commented on src/tramo_horario.ts
> +    private _horaComienzo : [number, number];
> Si no vas a usar un bucle para recorrerlo, no uses un array para representarlo, usa un diccionario. Es más informativo y claro `.hora` y `.minuto` que [0] y [1]

¡De acuerdo!

2022-11-28 18:12 UTC, JJ commented on src/tarea.ts
> +    private _dia: Date;
¿y dónde está documentado eso? ¿Donde mejor que en el nombre?

2022-11-28 18:13 UTC, fjromeero commented on src/huecos_libres_dia.ts
> +    private _intervalos: Array<TramoHorario>
> Fíjate en el issue #13 que es con el que estás trabajando. Plantea un problema, y ahí está la cosa más o menos clara. Sin embargo, dice "el usuario tenga cosas que hacer en cada momento". Tenemos dos problemas aquí. El primero se resuelve con domain driven design: ese te dice que tienes que tener un lenguaje común entre el dominio del problema y el código. Sin embargo, en el dominio del problema hablas de "cosas que haya que hacer en ese momento" y aquí de "intervalos". ¿Qué contiene esto? ¿Las cosas que tiene que hacer en cada momento? ¿O, como dice la clase, HuecosLibresDia? Pero aparentemente le estás asignando (abajo) simplemente lo que le pasan en el constructor. Mira de nuevo [los errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-12.md#objetivo-2). _Los argumentos de un constructor no tienen por qué ser directamente lo que se use como atributo_. Mira también los otros comentarios. ¿Te parece que habría algún valor para el cliente que añadir aquí?

¿No debería añadir el cliente cuando le es posible realizar tareas?

2022-11-28 18:16 UTC, fjromeero commented on src/tarea.ts
> +    private _dia: Date;
> ¿y dónde está documentado eso? ¿Donde mejor que en el nombre?

Huy de acuerdo,

2022-11-28 18:22 UTC, fjromeero commented on src/huecos_libres_dia.ts
> +    constructor(dia: Date, intervalos: Array<TramoHorario>){
> Vamos a ver. Esto no tiene nada que ver con el objetivo, pero piensa un poco. `dia` e `intervalos` son argumentos para el constructor, lo que significa que, quien quiera que cree el objeto, va a poder acceder públicamente a sus valores. ¿Tiene algún sentido que los pongas como privados? Mira, por favor, los [errores frecuentes de esta semana](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-12.md#objetivo-2). En general, el código debe añadir valor a los datos que encapsule; una forma de añadir valor es calcular o crear otros datos a partir de los existentes, de forma que no haya que calcularlos (repetidamente) más adelante. En este caso, parece claro que no añade ningún valor. Los agrupa (pero ya lo estarían donde quiera que se le haya llamado) y los cambia de nombre. ¿Qué valor tiene eso?
> 
> Es más, es que la clase se llama `HuecosLibresDia`. ¿Dónde están esos huecos libres? Si ya están en `intervalos`, ¿para qué los metes aquí?
> 

Los introduzco aquí porque para un día en concreto habrá x intervalos, pero es cierto que añadiendo una fecha a esos `intervalos`,  `HuecosLibresDia` es inutil.

> En general, todo código tiene un propósito. Si no entiendes cuál es ese propósito, y te estás limitando a trasladar los objetos y atributos que se te hayan ocurrido, no estás entendiendo el propósito del código.
> 
> Y para entender el propósito hay que plantear el problema. Qué datos se tienen, qué datos se quieren obtener, y a partir de ahí, decidir qué hay que almacenar.

2022-11-28 18:58 UTC, fjromeero commented on src/huecos_libres_dia.ts
> +    private _intervalos: Array<TramoHorario>
> ¿Qué más da quién lo añada? De lo que se trata de de hallar un _modelo_ del problema.

Entonces, ¿los constructores no son necesarios para esta modelización?

2022-11-28 19:17 UTC, JJ commented on src/huecos_libres_dia.ts
> +    private _intervalos: Array<TramoHorario>
Los constructores son imprescindibles. Pero tienen que *construir* algo, no simplemente meter cosas en sitios con otro nombre.

2022-11-28 22:33 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-29 10:35 UTC, JJ commented
> 
> Sobre la planificación y la programación:
> 
>     * [ ]  ¿Los issues representan un problema, y no una tarea?

Esto es esencial. Si siguen sin representar un problema, vas a seguir haciendo código que no corresponda a los deseos del usuario.

> 
>     * [ ]  ¿Todos los issues creados están asignados a una HU?

Exactamente igual.

2022-11-29 10:36 UTC, JJ commented
Los tres últimos commits no se refieren a ningún issue y por tanto a ninguna historia de usuario. Es imposible saber si son correctos o no, porque no se sabe qué problema resuelven.

2022-11-29 10:40 UTC, JJ requested changes
Casi, pero todavía queda un pequeño trecho. Te agradecería que lo miraras.

2022-11-29 10:40 UTC, JJ commented on iv.yaml
> +  - src/huecos_libres_dia.ts
Este fichero no existe.

2022-11-29 10:40 UTC, JJ commented on src/tramo_horario.ts
> +export type Hora={
¿Un tipo `Hora` incluye un atributo `hora` y otro más?
Poner nombre a las cosas no es trivial. Trata de encontrar el mejor nombre para cada cosa.

2022-11-29 10:40 UTC, JJ commented on src/tramo_horario.ts
> +    hora: number;
Trabajar con un `type` en vez de con una clase te va a impedir validar esto. Ahora mismo se podría definir perfectamente hora = 0.33 y minutos = 898.3

2022-11-29 22:58 UTC, fjromeero commented on src/tramo_horario.ts
> +export type Hora={
> ¿Un tipo `Hora` incluye un atributo `hora` y otro más? Poner nombre a las cosas no es trivial. Trata de encontrar el mejor nombre para cada cosa.

Realmente no se me ocurre ninguna otra forma de nombrarlo que no sea `Hora` y que lo represente de manera correcta. Lo unico que tal vez podria ser es `Momento` pero no estoy seguro.

2022-11-30 19:04 UTC, fjromeero commented
Listo para revisión @JJ

2022-11-30 19:08 UTC, JJ approved these changes
:+1: y buen trabajo.

2022-11-30 19:08 UTC, JJ commented on src/momento.ts
> +        this.hora = h;
Sigues sin validarlo, pero eso ya que lo haga @JoseCarlosJC

2022-11-30 19:14 UTC, fjromeero commented on src/momento.ts
> +        this.hora = h;
De acuerdo

2022-11-30 19:14 UTC, fjromeero commented
> 👍 y buen trabajo.

Gracias a usted por la paciencia

2022-11-30 19:16 UTC, fjromeero commented
@JoseCarlosJC  ya estaría

2023-01-09 09:35 UTC, merged